const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const albums=[{title:'Midnight Signals',artist:'Aster Vale',year:'2026',length:'4:18',art:'linear-gradient(135deg,#061532,#2834ff 55%,#ef13bd)'},{title:'Red Horizon',artist:'Nova Rouge',year:'2026',length:'3:41',art:'linear-gradient(135deg,#10040a,#ed173c 58%,#4d071a)'},{title:'Purple Static',artist:'Night Arcade',year:'2025',length:'3:54',art:'linear-gradient(135deg,#160029,#8828ff,#ed00ef)'},{title:'Heatwave',artist:'Low Lights',year:'2025',length:'4:02',art:'linear-gradient(135deg,#180509,#b9092b,#09070d)'},{title:'Blue Rooms',artist:'Satellite Kids',year:'2026',length:'3:32',art:'linear-gradient(135deg,#021d37,#00c8ef,#131043)'}];
let current=0,playing=false,seconds=88,timer;const notify=m=>{const t=$('#toast');t.textContent=m;t.classList.add('show');clearTimeout(notify.t);notify.t=setTimeout(()=>t.classList.remove('show'),1600)};
function drawCards(list=albums.slice(1)){$('#cards').innerHTML=list.slice(0,4).map(a=>`<article class="card" data-index="${albums.indexOf(a)}"><div class="card-art" style="--art:${a.art}"></div><div class="card-info">${a.title} · ${a.artist}</div></article>`).join('');$$('.card').forEach(c=>c.onclick=()=>select(+c.dataset.index,true))}
function select(index,auto=false){current=(index+albums.length)%albums.length;const a=albums[current];$('#albumTitle').textContent=a.title;$('#albumArtist').textContent=`${a.artist} · ${a.year}`;$('#trackTitle').textContent=a.title;$('#trackArtist').textContent=a.artist;$('#duration').textContent=a.length;$('#miniCover').style.background=`repeating-radial-gradient(circle,#07101d 0 5px,#102644 6px 8px),${a.art}`;seconds=0;$('#seek').value=0;$('#elapsed').textContent='0:00';if(auto&&!playing)togglePlay();notify(`${auto?'Now playing':'Selected'} — ${a.title}`)}
function togglePlay(){playing=!playing;$('#play').textContent=playing?'Ⅱ':'▶';clearInterval(timer);if(playing)timer=setInterval(()=>{seconds=(seconds+1)%259;$('#elapsed').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;$('#seek').value=Math.round(seconds/258*100)},1000)}
$('#previousAlbum').onclick=()=>select(current-1);$('#nextAlbum').onclick=()=>select(current+1);$('#prevTrack').onclick=()=>select(current-1,true);$('#nextTrack').onclick=()=>select(current+1,true);$('#play').onclick=togglePlay;$('#seek').oninput=e=>{seconds=Math.round(+e.target.value*2.58);$('#elapsed').textContent=`${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`};
$('#like').onclick=e=>{e.currentTarget.classList.toggle('on');e.currentTarget.textContent=e.currentTarget.classList.contains('on')?'♥':'♡';notify(e.currentTarget.classList.contains('on')?'Added to Liked':'Removed from Liked')};['shuffle','repeat'].forEach(id=>$('#'+id).onclick=e=>{e.currentTarget.classList.toggle('on');notify(`${id[0].toUpperCase()+id.slice(1)} ${e.currentTarget.classList.contains('on')?'on':'off'}`)});$('#newPlaylist').onclick=()=>notify('New playlist created');$('#seeAll').onclick=()=>notify('Showing this week’s releases');
$$('nav button').forEach(b=>b.onclick=()=>{$$('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#sectionLabel').textContent=b.dataset.view;$('#pageTitle').textContent=b.dataset.view==='Albums'?'Popular':b.dataset.view;notify(`${b.dataset.view} opened`)});$('#search').oninput=e=>{const q=e.target.value.toLowerCase();drawCards(albums.filter(a=>(a.title+a.artist).toLowerCase().includes(q)))};drawCards();
